OGRESHARED_WEAK_CPP_SRCS= \
	OgreMain/src/Animation/OgreBone.cpp \
	OgreMain/src/GLX/OgreConfigDialog.cpp \
	OgreMain/src/GLX/OgreErrorDialog.cpp \
	OgreMain/src/GLX/OgreTimer.cpp \
	OgreMain/src/OgreAlignedAllocator.cpp \
	OgreMain/src/OgreAnimable.cpp \
	OgreMain/src/OgreAnimation.cpp \
	OgreMain/src/OgreAnimationState.cpp \
	OgreMain/src/OgreAnimationTrack.cpp \
	OgreMain/src/OgreArchive.cpp \
	OgreMain/src/OgreArchiveManager.cpp \
	OgreMain/src/OgreAutoParamDataSource.cpp \
	OgreMain/src/OgreAxisAlignedBox.cpp \
	OgreMain/src/OgreBillboardChain.cpp \
	OgreMain/src/OgreBillboard.cpp \
	OgreMain/src/OgreBillboardParticleRenderer.cpp \
	OgreMain/src/OgreBillboardSet.cpp \
	OgreMain/src/OgreCamera.cpp \
	OgreMain/src/OgreCodec.cpp \
	OgreMain/src/OgreColourValue.cpp \
	OgreMain/src/OgreCommon.cpp \
	OgreMain/src/OgreCompositionTargetPass.cpp \
	OgreMain/src/OgreCompositionTechnique.cpp \
	OgreMain/src/OgreCompositorChain.cpp \
	OgreMain/src/OgreCompositor.cpp \
	OgreMain/src/OgreCompositorInstance.cpp \
	OgreMain/src/OgreCompositorManager.cpp \
	OgreMain/src/OgreConfigFile.cpp \
	OgreMain/src/OgreControllerManager.cpp \
	OgreMain/src/OgreConvexBody.cpp \
	OgreMain/src/OgreDataStream.cpp \
	OgreMain/src/OgreDDSCodec.cpp \
	OgreMain/src/OgreDefaultHardwareBufferManager.cpp \
	OgreMain/src/OgreDefaultSceneQueries.cpp \
	OgreMain/src/OgreDepthBuffer.cpp \
	OgreMain/src/OgreDistanceLodStrategy.cpp \
	OgreMain/src/OgreDualQuaternion.cpp \
	OgreMain/src/OgreDynLib.cpp \
	OgreMain/src/OgreDynLibManager.cpp \
	OgreMain/src/OgreEdgeListBuilder.cpp \
	OgreMain/src/OgreEntity.cpp \
	OgreMain/src/OgreException.cpp \
	OgreMain/src/OgreExternalTextureSource.cpp \
	OgreMain/src/OgreExternalTextureSourceManager.cpp \
	OgreMain/src/OgreFileSystem.cpp \
	OgreMain/src/OgreFreeImageCodec.cpp \
	OgreMain/src/OgreFrustum.cpp \
	OgreMain/src/OgreGpuProgram.cpp \
	OgreMain/src/OgreGpuProgramManager.cpp \
	OgreMain/src/OgreGpuProgramParams.cpp \
	OgreMain/src/OgreGpuProgramUsage.cpp \
	OgreMain/src/OgreHardwareBufferManager.cpp \
	OgreMain/src/OgreHardwareCounterBuffer.cpp \
	OgreMain/src/OgreHardwareIndexBuffer.cpp \
	OgreMain/src/OgreHardwareOcclusionQuery.cpp \
	OgreMain/src/OgreHardwarePixelBuffer.cpp \
	OgreMain/src/OgreHardwareUniformBuffer.cpp \
	OgreMain/src/OgreHardwareVertexBuffer.cpp \
	OgreMain/src/OgreHighLevelGpuProgram.cpp \
	OgreMain/src/OgreHighLevelGpuProgramManager.cpp \
	OgreMain/src/OgreImage.cpp \
	OgreMain/src/OgreInstanceBatch.cpp \
	OgreMain/src/OgreInstanceBatchHW.cpp \
	OgreMain/src/OgreInstanceBatchHW_VTF.cpp \
	OgreMain/src/OgreInstanceBatchShader.cpp \
	OgreMain/src/OgreInstanceBatchVTF.cpp \
	OgreMain/src/OgreInstancedEntity.cpp \
	OgreMain/src/OgreInstancedGeometry.cpp \
	OgreMain/src/OgreInstanceManager.cpp \
	OgreMain/src/OgreKeyFrame.cpp \
	OgreMain/src/OgreLight.cpp \
	OgreMain/src/OgreLodStrategy.cpp \
	OgreMain/src/OgreLodStrategyManager.cpp \
	OgreMain/src/OgreLog.cpp \
	OgreMain/src/OgreLogManager.cpp \
	OgreMain/src/OgreManualObject.cpp \
	OgreMain/src/OgreMaterial.cpp \
	OgreMain/src/OgreMaterialManager.cpp \
	OgreMain/src/OgreMaterialSerializer.cpp \
	OgreMain/src/OgreMath.cpp \
	OgreMain/src/OgreMatrix3.cpp \
	OgreMain/src/OgreMatrix4.cpp \
	OgreMain/src/OgreMemoryAllocatedObject.cpp \
	OgreMain/src/OgreMemoryNedAlloc.cpp \
	OgreMain/src/OgreMesh.cpp \
	OgreMain/src/OgreMeshManager.cpp \
	OgreMain/src/OgreMeshSerializer.cpp \
	OgreMain/src/OgreMeshSerializerImpl.cpp \
	OgreMain/src/OgreMovableObject.cpp \
	OgreMain/src/OgreMovablePlane.cpp \
	OgreMain/src/OgreNode.cpp \
	OgreMain/src/OgreNumerics.cpp \
	OgreMain/src/OgreOptimisedUtil.cpp \
	OgreMain/src/OgreOptimisedUtilGeneral.cpp \
	OgreMain/src/OgreOptimisedUtilSSE.cpp \
	OgreMain/src/OgreParticle.cpp \
	OgreMain/src/OgreParticleEmitterCommands.cpp \
	OgreMain/src/OgreParticleEmitter.cpp \
	OgreMain/src/OgreParticleIterator.cpp \
	OgreMain/src/OgreParticleSystem.cpp \
	OgreMain/src/OgreParticleSystemManager.cpp \
	OgreMain/src/OgrePass.cpp \
	OgreMain/src/OgrePatchMesh.cpp \
	OgreMain/src/OgrePatchSurface.cpp \
	OgreMain/src/OgrePixelCountLodStrategy.cpp \
	OgreMain/src/OgrePixelFormat.cpp \
	OgreMain/src/OgrePlane.cpp \
	OgreMain/src/OgrePlatformInformation.cpp \
	OgreMain/src/OgrePolygon.cpp \
	OgreMain/src/OgrePose.cpp \
	OgreMain/src/OgrePrecompiledHeaders.cpp \
	OgreMain/src/OgrePredefinedControllers.cpp \
	OgreMain/src/OgrePrefabFactory.cpp \
	OgreMain/src/OgreProfiler.cpp \
	OgreMain/src/OgreProgressiveMeshGenerator.cpp \
	OgreMain/src/OgrePVRTCCodec.cpp \
	OgreMain/src/OgreQuaternion.cpp \
	OgreMain/src/OgreQueuedProgressiveMeshGenerator.cpp \
	OgreMain/src/OgreRectangle2D.cpp \
	OgreMain/src/OgreRenderQueue.cpp \
	OgreMain/src/OgreRenderQueueInvocation.cpp \
	OgreMain/src/OgreRenderQueueSortingGrouping.cpp \
	OgreMain/src/OgreRenderSystemCapabilities.cpp \
	OgreMain/src/OgreRenderSystemCapabilitiesManager.cpp \
	OgreMain/src/OgreRenderSystemCapabilitiesSerializer.cpp \
	OgreMain/src/OgreRenderSystem.cpp \
	OgreMain/src/OgreRenderTarget.cpp \
	OgreMain/src/OgreRenderTexture.cpp \
	OgreMain/src/OgreRenderToVertexBuffer.cpp \
	OgreMain/src/OgreRenderWindow.cpp \
	OgreMain/src/OgreResourceBackgroundQueue.cpp \
	OgreMain/src/OgreResource.cpp \
	OgreMain/src/OgreResourceGroupManager.cpp \
	OgreMain/src/OgreResourceManager.cpp \
	OgreMain/src/OgreRibbonTrail.cpp \
	OgreMain/src/OgreRoot.cpp \
	OgreMain/src/OgreRotationSpline.cpp \
	OgreMain/src/OgreSceneManager.cpp \
	OgreMain/src/OgreSceneManagerEnumerator.cpp \
	OgreMain/src/OgreSceneNode.cpp \
	OgreMain/src/OgreSceneQuery.cpp \
	OgreMain/src/OgreScriptCompiler.cpp \
	OgreMain/src/OgreScriptLexer.cpp \
	OgreMain/src/OgreScriptParser.cpp \
	OgreMain/src/OgreScriptTranslator.cpp \
	OgreMain/src/OgreSearchOps.cpp \
	OgreMain/src/OgreSerializer.cpp \
	OgreMain/src/OgreShadowCameraSetup.cpp \
	OgreMain/src/OgreShadowCameraSetupFocused.cpp \
	OgreMain/src/OgreShadowCameraSetupLiSPSM.cpp \
	OgreMain/src/OgreShadowCameraSetupPlaneOptimal.cpp \
	OgreMain/src/OgreShadowCameraSetupPSSM.cpp \
	OgreMain/src/OgreShadowCaster.cpp \
	OgreMain/src/OgreShadowTextureManager.cpp \
	OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp \
	OgreMain/src/OgreSimpleRenderable.cpp \
	OgreMain/src/OgreSimpleSpline.cpp \
	OgreMain/src/OgreSkeleton.cpp \
	OgreMain/src/OgreSkeletonInstance.cpp \
	OgreMain/src/OgreSkeletonManager.cpp \
	OgreMain/src/OgreSkeletonSerializer.cpp \
	OgreMain/src/OgreSmallVector.cpp \
	OgreMain/src/OgreStaticGeometry.cpp \
	OgreMain/src/OgreStringConverter.cpp \
	OgreMain/src/OgreString.cpp \
	OgreMain/src/OgreStringInterface.cpp \
	OgreMain/src/OgreSubEntity.cpp \
	OgreMain/src/OgreSubMesh.cpp \
	OgreMain/src/OgreTagPoint.cpp \
	OgreMain/src/OgreTangentSpaceCalc.cpp \
	OgreMain/src/OgreTechnique.cpp \
	OgreMain/src/OgreTexture.cpp \
	OgreMain/src/OgreTextureManager.cpp \
	OgreMain/src/OgreTextureUnitState.cpp \
	OgreMain/src/OgreUnifiedHighLevelGpuProgram.cpp \
	OgreMain/src/OgreUserObjectBindings.cpp \
	OgreMain/src/OgreUTFString.cpp \
	OgreMain/src/OgreVector2.cpp \
	OgreMain/src/OgreVector3.cpp \
	OgreMain/src/OgreVector4.cpp \
	OgreMain/src/OgreVertexIndexData.cpp \
	OgreMain/src/OgreViewport.cpp \
	OgreMain/src/OgreWindowEventUtilities.cpp \
	OgreMain/src/OgreWireBoundingBox.cpp \
	OgreMain/src/OgreWorkQueue.cpp \
	OgreMain/src/OgreZip.cpp \
	OgreMain/src/Threading/OgreDefaultWorkQueueStandard.cpp \


OGRE_WEAK_CPP_SRCS= \
	$(OGRESHARED_WEAK_CPP_SRCS) \
	PlugIns/CgProgramManager/src/OgreCgFxScriptLoader.cpp \
	PlugIns/CgProgramManager/src/OgreCgPlugin.cpp \
	PlugIns/CgProgramManager/src/OgreCgProgram.cpp \
	PlugIns/CgProgramManager/src/OgreCgProgramFactory.cpp \
	PlugIns/CgProgramManager/src/OgreCgProgramManagerDll.cpp \
	PlugIns/OctreeSceneManager/src/OgreOctreeCamera.cpp \
	PlugIns/OctreeSceneManager/src/OgreOctree.cpp \
	PlugIns/OctreeSceneManager/src/OgreOctreeNode.cpp \
	PlugIns/OctreeSceneManager/src/OgreOctreePlugin.cpp \
	PlugIns/OctreeSceneManager/src/OgreOctreeSceneManager.cpp \
	PlugIns/OctreeSceneManager/src/OgreOctreeSceneQuery.cpp \
	RenderSystems/GL/src/atifs/src/ATI_FS_GLGpuProgram.cpp \
	RenderSystems/GL/src/atifs/src/Compiler2Pass.cpp \
	RenderSystems/GL/src/atifs/src/ps_1_4.cpp \
	RenderSystems/GL/src/glew.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLExtSupport.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLGpuProgram.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgram.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLLinkProgramManager.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLPreprocessor.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLProgram.cpp \
	RenderSystems/GL/src/GLSL/src/OgreGLSLProgramFactory.cpp \
	RenderSystems/GL/src/GLX/OgreGLXContext.cpp \
	RenderSystems/GL/src/GLX/OgreGLXGLSupport.cpp \
	RenderSystems/GL/src/GLX/OgreGLXRenderTexture.cpp \
	RenderSystems/GL/src/GLX/OgreGLXWindow.cpp \
	RenderSystems/GL/src/nvparse/avp1.0_impl.cpp \
	RenderSystems/GL/src/nvparse/nvparse.cpp \
	RenderSystems/GL/src/nvparse/nvparse_errors.cpp \
	RenderSystems/GL/src/nvparse/_ps1.0_lexer.cpp \
	RenderSystems/GL/src/nvparse/_ps1.0_parser.cpp \
	RenderSystems/GL/src/nvparse/ps1.0_program.cpp \
	RenderSystems/GL/src/nvparse/rc1.0_combiners.cpp \
	RenderSystems/GL/src/nvparse/rc1.0_final.cpp \
	RenderSystems/GL/src/nvparse/rc1.0_general.cpp \
	RenderSystems/GL/src/nvparse/_rc1.0_lexer.cpp \
	RenderSystems/GL/src/nvparse/_rc1.0_parser.cpp \
	RenderSystems/GL/src/nvparse/ts1.0_inst.cpp \
	RenderSystems/GL/src/nvparse/ts1.0_inst_list.cpp \
	RenderSystems/GL/src/nvparse/_ts1.0_lexer.cpp \
	RenderSystems/GL/src/nvparse/_ts1.0_parser.cpp \
	RenderSystems/GL/src/nvparse/vcp1.0_impl.cpp \
	RenderSystems/GL/src/nvparse/vp1.0_impl.cpp \
	RenderSystems/GL/src/nvparse/vs1.0_inst.cpp \
	RenderSystems/GL/src/nvparse/vs1.0_inst_list.cpp \
	RenderSystems/GL/src/nvparse/_vs1.0_lexer.cpp \
	RenderSystems/GL/src/nvparse/_vs1.0_parser.cpp \
	RenderSystems/GL/src/nvparse/vsp1.0_impl.cpp \
	RenderSystems/GL/src/OgreGLATIFSInit.cpp \
	RenderSystems/GL/src/OgreGLContext.cpp \
	RenderSystems/GL/src/OgreGLDefaultHardwareBufferManager.cpp \
	RenderSystems/GL/src/OgreGLDepthBuffer.cpp \
	RenderSystems/GL/src/OgreGLFBOMultiRenderTarget.cpp \
	RenderSystems/GL/src/OgreGLFBORenderTexture.cpp \
	RenderSystems/GL/src/OgreGLFrameBufferObject.cpp \
	RenderSystems/GL/src/OgreGLGpuNvparseProgram.cpp \
	RenderSystems/GL/src/OgreGLGpuProgram.cpp \
	RenderSystems/GL/src/OgreGLGpuProgramManager.cpp \
	RenderSystems/GL/src/OgreGLHardwareBufferManager.cpp \
	RenderSystems/GL/src/OgreGLHardwareIndexBuffer.cpp \
	RenderSystems/GL/src/OgreGLHardwareOcclusionQuery.cpp \
	RenderSystems/GL/src/OgreGLHardwarePixelBuffer.cpp \
	RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp \
	RenderSystems/GL/src/OgreGLPBRenderTexture.cpp \
	RenderSystems/GL/src/OgreGLPixelFormat.cpp \
	RenderSystems/GL/src/OgreGLPlugin.cpp \
	RenderSystems/GL/src/OgreGLRenderSystem.cpp \
	RenderSystems/GL/src/OgreGLRenderTexture.cpp \
	RenderSystems/GL/src/OgreGLRenderToVertexBuffer.cpp \
	RenderSystems/GL/src/OgreGLStateCacheManager.cpp \
	RenderSystems/GL/src/OgreGLSupport.cpp \
	RenderSystems/GL/src/OgreGLTexture.cpp \
	RenderSystems/GL/src/OgreGLTextureManager.cpp \
	RenderSystems/GL/src/OgreGLUniformCache.cpp \
	RenderSystems/GL/src/StateCacheManager/OgreGLNullStateCacheManagerImp.cpp \
	RenderSystems/GL/src/StateCacheManager/OgreGLNullUniformCacheImp.cpp \

OGRE_INCLUDE_SRCS = \
	OgreBuildSettings.h \
	OgreMain/include/Animation/OgreBone.h \
	OgreMain/include/asm_math.h \
	OgreMain/include/GLX/OgreConfigDialogImp.h \
	OgreMain/include/GLX/OgreErrorDialogImp.h \
	OgreMain/include/GLX/OgreTimerImp.h \
	OgreMain/include/gtk/OgreConfigDialogImp.h \
	OgreMain/include/gtk/OgreErrorDialogImp.h \
	OgreMain/include/NaCl/OgreConfigDialogImp.h \
	OgreMain/include/NaCl/OgreErrorDialogImp.h \
	OgreMain/include/NaCl/OgreTimerImp.h \
	OgreMain/include/OgreAlignedAllocator.h \
	OgreMain/include/OgreAnimable.h \
	OgreMain/include/OgreAnimation.h \
	OgreMain/include/OgreAnimationState.h \
	OgreMain/include/OgreAnimationTrack.h \
	OgreMain/include/OgreAny.h \
	OgreMain/include/OgreArchiveFactory.h \
	OgreMain/include/OgreArchive.h \
	OgreMain/include/OgreArchiveManager.h \
	OgreMain/include/OgreAtomicWrappers.h \
	OgreMain/include/OgreAutoParamDataSource.h \
	OgreMain/include/OgreAxisAlignedBox.h \
	OgreMain/include/OgreBillboardChain.h \
	OgreMain/include/OgreBillboard.h \
	OgreMain/include/OgreBillboardParticleRenderer.h \
	OgreMain/include/OgreBillboardSet.h \
	OgreMain/include/OgreBitwise.h \
	OgreMain/include/OgreBlendMode.h \
	OgreMain/include/OgreCamera.h \
	OgreMain/include/OgreCodec.h \
	OgreMain/include/OgreColourValue.h \
	OgreMain/include/OgreCommon.h \
	OgreMain/include/OgreCompositionTargetPass.h \
	OgreMain/include/OgreCompositionTechnique.h \
	OgreMain/include/OgreCompositorChain.h \
	OgreMain/include/OgreCompositor.h \
	OgreMain/include/OgreCompositorInstance.h \
	OgreMain/include/OgreCompositorLogic.h \
	OgreMain/include/OgreCompositorManager.h \
	OgreMain/include/OgreConfigDialog.h \
	OgreMain/include/OgreConfigFile.h \
	OgreMain/include/OgreConfig.h \
	OgreMain/include/OgreConfigOptionMap.h \
	OgreMain/include/OgreController.h \
	OgreMain/include/OgreControllerManager.h \
	OgreMain/include/OgreConvexBody.h \
	OgreMain/include/OgreDataStream.h \
	OgreMain/include/OgreDDSCodec.h \
	OgreMain/include/OgreDefaultHardwareBufferManager.h \
	OgreMain/include/OgreDeflate.h \
	OgreMain/include/OgreDepthBuffer.h \
	OgreMain/include/OgreDistanceLodStrategy.h \
	OgreMain/include/OgreDualQuaternion.h \
	OgreMain/include/OgreDynLib.h \
	OgreMain/include/OgreDynLibManager.h \
	OgreMain/include/OgreEdgeListBuilder.h \
	OgreMain/include/OgreEntity.h \
	OgreMain/include/OgreErrorDialog.h \
	OgreMain/include/OgreETC1Codec.h \
	OgreMain/include/OgreException.h \
	OgreMain/include/OgreExternalTextureSource.h \
	OgreMain/include/OgreExternalTextureSourceManager.h \
	OgreMain/include/OgreFactoryObj.h \
	OgreMain/include/OgreFileSystem.h \
	OgreMain/include/OgreFileSystemLayer.h \
	OgreMain/include/OgreFrameListener.h \
	OgreMain/include/OgreFreeImageCodec.h \
	OgreMain/include/OgreFrustum.h \
	OgreMain/include/OgreGpuProgram.h \
	OgreMain/include/OgreGpuProgramManager.h \
	OgreMain/include/OgreGpuProgramParams.h \
	OgreMain/include/OgreGpuProgramUsage.h \
	OgreMain/include/Ogre.h \
	OgreMain/include/OgreHardwareBuffer.h \
	OgreMain/include/OgreHardwareBufferManager.h \
	OgreMain/include/OgreHardwareCounterBuffer.h \
	OgreMain/include/OgreHardwareIndexBuffer.h \
	OgreMain/include/OgreHardwareOcclusionQuery.h \
	OgreMain/include/OgreHardwarePixelBuffer.h \
	OgreMain/include/OgreHardwareUniformBuffer.h \
	OgreMain/include/OgreHardwareVertexBuffer.h \
	OgreMain/include/OgreHeaderPrefix.h \
	OgreMain/include/OgreHeaderSuffix.h \
	OgreMain/include/OgreHighLevelGpuProgram.h \
	OgreMain/include/OgreHighLevelGpuProgramManager.h \
	OgreMain/include/OgreImageCodec.h \
	OgreMain/include/OgreImage.h \
	OgreMain/include/OgreInstanceBatch.h \
	OgreMain/include/OgreInstanceBatchHW.h \
	OgreMain/include/OgreInstanceBatchHW_VTF.h \
	OgreMain/include/OgreInstanceBatchShader.h \
	OgreMain/include/OgreInstanceBatchVTF.h \
	OgreMain/include/OgreInstancedEntity.h \
	OgreMain/include/OgreInstancedGeometry.h \
	OgreMain/include/OgreInstanceManager.h \
	OgreMain/include/OgreIteratorRange.h \
	OgreMain/include/OgreIteratorWrapper.h \
	OgreMain/include/OgreIteratorWrappers.h \
	OgreMain/include/OgreKeyFrame.h \
	OgreMain/include/OgreLight.h \
	OgreMain/include/OgreLodConfig.h \
	OgreMain/include/OgreLodListener.h \
	OgreMain/include/OgreLodStrategy.h \
	OgreMain/include/OgreLodStrategyManager.h \
	OgreMain/include/OgreLog.h \
	OgreMain/include/OgreLogManager.h \
	OgreMain/include/OgreManualObject.h \
	OgreMain/include/OgreMaterial.h \
	OgreMain/include/OgreMaterialManager.h \
	OgreMain/include/OgreMaterialSerializer.h \
	OgreMain/include/OgreMath.h \
	OgreMain/include/OgreMatrix3.h \
	OgreMain/include/OgreMatrix4.h \
	OgreMain/include/OgreMemoryAllocatedObject.h \
	OgreMain/include/OgreMemoryAllocatorConfig.h \
	OgreMain/include/OgreMemoryNedAlloc.h \
	OgreMain/include/OgreMemoryNedPooling.h \
	OgreMain/include/OgreMemoryStdAlloc.h \
	OgreMain/include/OgreMemorySTLAllocator.h \
	OgreMain/include/OgreMemoryTracker.h \
	OgreMain/include/OgreMeshFileFormat.h \
	OgreMain/include/OgreMesh.h \
	OgreMain/include/OgreMeshManager.h \
	OgreMain/include/OgreMeshSerializer.h \
	OgreMain/include/OgreMeshSerializerImpl.h \
	OgreMain/include/OgreMovableObject.h \
	OgreMain/include/OgreMovablePlane.h \
	OgreMain/include/OgreNode.h \
	OgreMain/include/OgreNumerics.h \
	OgreMain/include/OgreOptimisedUtil.h \
	OgreMain/include/OgreParticleAffectorFactory.h \
	OgreMain/include/OgreParticleAffector.h \
	OgreMain/include/OgreParticleEmitterCommands.h \
	OgreMain/include/OgreParticleEmitterFactory.h \
	OgreMain/include/OgreParticleEmitter.h \
	OgreMain/include/OgreParticle.h \
	OgreMain/include/OgreParticleIterator.h \
	OgreMain/include/OgreParticleScriptCompiler.h \
	OgreMain/include/OgreParticleSystem.h \
	OgreMain/include/OgreParticleSystemManager.h \
	OgreMain/include/OgreParticleSystemRenderer.h \
	OgreMain/include/OgrePass.h \
	OgreMain/include/OgrePatchMesh.h \
	OgreMain/include/OgrePatchSurface.h \
	OgreMain/include/OgrePixelCountLodStrategy.h \
	OgreMain/include/OgrePixelFormat.h \
	OgreMain/include/OgrePlaneBoundedVolume.h \
	OgreMain/include/OgrePlane.h \
	OgreMain/include/OgrePlatform.h \
	OgreMain/include/OgrePlatformInformation.h \
	OgreMain/include/OgrePlugin.h \
	OgreMain/include/OgrePolygon.h \
	OgreMain/include/OgrePose.h \
	OgreMain/include/OgrePredefinedControllers.h \
	OgreMain/include/OgrePrefabFactory.h \
	OgreMain/include/OgrePrerequisites.h \
	OgreMain/include/OgreProfiler.h \
	OgreMain/include/OgreProgressiveMeshGenerator.h \
	OgreMain/include/OgrePVRTCCodec.h \
	OgreMain/include/OgreQuaternion.h \
	OgreMain/include/OgreQueuedProgressiveMeshGenerator.h \
	OgreMain/include/OgreRadixSort.h \
	OgreMain/include/OgreRay.h \
	OgreMain/include/OgreRectangle2D.h \
	OgreMain/include/OgreRenderable.h \
	OgreMain/include/OgreRenderObjectListener.h \
	OgreMain/include/OgreRenderOperation.h \
	OgreMain/include/OgreRenderQueue.h \
	OgreMain/include/OgreRenderQueueInvocation.h \
	OgreMain/include/OgreRenderQueueListener.h \
	OgreMain/include/OgreRenderQueueSortingGrouping.h \
	OgreMain/include/OgreRenderSystemCapabilities.h \
	OgreMain/include/OgreRenderSystemCapabilitiesManager.h \
	OgreMain/include/OgreRenderSystemCapabilitiesSerializer.h \
	OgreMain/include/OgreRenderSystem.h \
	OgreMain/include/OgreRenderTarget.h \
	OgreMain/include/OgreRenderTargetListener.h \
	OgreMain/include/OgreRenderTexture.h \
	OgreMain/include/OgreRenderToVertexBuffer.h \
	OgreMain/include/OgreRenderWindow.h \
	OgreMain/include/OgreResourceBackgroundQueue.h \
	OgreMain/include/OgreResourceGroupManager.h \
	OgreMain/include/OgreResource.h \
	OgreMain/include/OgreResourceManager.h \
	OgreMain/include/OgreRibbonTrail.h \
	OgreMain/include/OgreRoot.h \
	OgreMain/include/OgreRotationalSpline.h \
	OgreMain/include/OgreSceneManagerEnumerator.h \
	OgreMain/include/OgreSceneManager.h \
	OgreMain/include/OgreSceneNode.h \
	OgreMain/include/OgreSceneQuery.h \
	OgreMain/include/OgreScriptCompiler.h \
	OgreMain/include/OgreScriptLexer.h \
	OgreMain/include/OgreScriptLoader.h \
	OgreMain/include/OgreScriptParser.h \
	OgreMain/include/OgreScriptTranslator.h \
	OgreMain/include/OgreSearchOps.h \
	OgreMain/include/OgreSerializer.h \
	OgreMain/include/OgreShadowCameraSetupFocused.h \
	OgreMain/include/OgreShadowCameraSetup.h \
	OgreMain/include/OgreShadowCameraSetupLiSPSM.h \
	OgreMain/include/OgreShadowCameraSetupPlaneOptimal.h \
	OgreMain/include/OgreShadowCameraSetupPSSM.h \
	OgreMain/include/OgreShadowCaster.h \
	OgreMain/include/OgreShadowTextureManager.h \
	OgreMain/include/OgreShadowVolumeExtrudeProgram.h \
	OgreMain/include/OgreSharedPtr.h \
	OgreMain/include/OgreSimpleRenderable.h \
	OgreMain/include/OgreSimpleSpline.h \
	OgreMain/include/OgreSingleton.h \
	OgreMain/include/OgreSkeletonFileFormat.h \
	OgreMain/include/OgreSkeleton.h \
	OgreMain/include/OgreSkeletonInstance.h \
	OgreMain/include/OgreSkeletonManager.h \
	OgreMain/include/OgreSkeletonSerializer.h \
	OgreMain/include/OgreSmallVector.h \
	OgreMain/include/OgreSphere.h \
	OgreMain/include/OgreSpotShadowFadePng.h \
	OgreMain/include/OgreStableHeaders.h \
	OgreMain/include/OgreStaticFaceGroup.h \
	OgreMain/include/OgreStaticGeometry.h \
	OgreMain/include/OgreStdHeaders.h \
	OgreMain/include/OgreStreamSerialiser.h \
	OgreMain/include/OgreStringConverter.h \
	OgreMain/include/OgreString.h \
	OgreMain/include/OgreStringInterface.h \
	OgreMain/include/OgreStringVector.h \
	OgreMain/include/OgreSubEntity.h \
	OgreMain/include/OgreSubMesh.h \
	OgreMain/include/OgreTagPoint.h \
	OgreMain/include/OgreTangentSpaceCalc.h \
	OgreMain/include/OgreTechnique.h \
	OgreMain/include/OgreTexture.h \
	OgreMain/include/OgreTextureManager.h \
	OgreMain/include/OgreTextureUnitState.h \
	OgreMain/include/OgreTimer.h \
	OgreMain/include/OgreUnifiedHighLevelGpuProgram.h \
	OgreMain/include/OgreUserObjectBindings.h \
	OgreMain/include/OgreUTFString.h \
	OgreMain/include/OgreVector2.h \
	OgreMain/include/OgreVector3.h \
	OgreMain/include/OgreVector4.h \
	OgreMain/include/OgreVertexBoneAssignment.h \
	OgreMain/include/OgreVertexIndexData.h \
	OgreMain/include/OgreViewport.h \
	OgreMain/include/OgreWindowEventUtilities.h \
	OgreMain/include/OgreWireBoundingBox.h \
	OgreMain/include/OgreWorkQueue.h \
	OgreMain/include/OgreZip.h \
	OgreMain/include/Threading/OgreDefaultWorkQueue.h \
	OgreMain/include/Threading/OgreDefaultWorkQueueStandard.h \
	OgreMain/include/Threading/OgreDefaultWorkQueueTBB.h \
	OgreMain/include/Threading/OgreThreadDefinesBoost.h \
	OgreMain/include/Threading/OgreThreadDefines.h \
	OgreMain/include/Threading/OgreThreadDefinesNone.h \
	OgreMain/include/Threading/OgreThreadDefinesPoco.h \
	OgreMain/include/Threading/OgreThreadDefinesStd.h \
	OgreMain/include/Threading/OgreThreadDefinesTBB.h \
	OgreMain/include/Threading/OgreThreadHeadersBoost.h \
	OgreMain/include/Threading/OgreThreadHeaders.h \
	OgreMain/include/Threading/OgreThreadHeadersPoco.h \
	OgreMain/include/Threading/OgreThreadHeadersStd.h \
	OgreMain/include/Threading/OgreThreadHeadersTBB.h \
	OgreMain/src/GLX/GLX_backdrop.h \
	OgreMain/src/gtk/GLX_backdrop.h \
	OgreMain/src/nedmalloc/malloc.c.h \
	OgreMain/src/nedmalloc/nedmalloc.h \
	OgreMain/src/OgreImageResampler.h \
	OgreMain/src/OgrePixelConversions.h \
	OgreMain/src/OgreSIMDHelper.h \
	PlugIns/CgProgramManager/include/OgreCgFxScriptLoader.h \
	PlugIns/CgProgramManager/include/OgreCgPlugin.h \
	PlugIns/CgProgramManager/include/OgreCgPrerequisites.h \
	PlugIns/CgProgramManager/include/OgreCgProgramFactory.h \
	PlugIns/CgProgramManager/include/OgreCgProgram.h \
	PlugIns/OctreeSceneManager/include/OgreOctreeCamera.h \
	PlugIns/OctreeSceneManager/include/OgreOctree.h \
	PlugIns/OctreeSceneManager/include/OgreOctreeNode.h \
	PlugIns/OctreeSceneManager/include/OgreOctreePlugin.h \
	PlugIns/OctreeSceneManager/include/OgreOctreePrerequisites.h \
	PlugIns/OctreeSceneManager/include/OgreOctreeSceneManager.h \
	PlugIns/OctreeSceneManager/include/OgreOctreeSceneQuery.h \
	RenderSystems/GL3Plus/include/GL/gl3w.h \
	RenderSystems/GL3Plus/include/GL/glcorearb.h \
	RenderSystems/GL3Plus/include/GL/glext.h \
	RenderSystems/GL3Plus/include/GL/glxext.h \
	RenderSystems/GL3Plus/include/GL/glxtokens-backup.h \
	RenderSystems/GL3Plus/include/GL/wglext.h \
	RenderSystems/GL3Plus/include/GLX/OgreGLXContext.h \
	RenderSystems/GL3Plus/include/GLX/OgreGLXGLSupport.h \
	RenderSystems/GL3Plus/include/GLX/OgreGLXUtils.h \
	RenderSystems/GL3Plus/include/GLX/OgreGLXWindow.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusContext.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusDefaultHardwareBufferManager.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusDepthBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusFBOMultiRenderTarget.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusFBORenderTexture.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusFrameBufferObject.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusGpuProgram.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusGpuProgramManager.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwareBufferManager.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwareCounterBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwareIndexBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwareOcclusionQuery.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwarePixelBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwareUniformBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusHardwareVertexBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusPixelFormat.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusPlugin.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusPrerequisites.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusRenderSystem.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusRenderTexture.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusRenderToVertexBuffer.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusSupport.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusTexture.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusTextureManager.h \
	RenderSystems/GL3Plus/include/OgreGL3PlusVertexArrayObject.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLExtSupport.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLGpuProgram.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLLinkProgram.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLLinkProgramManager.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLPreprocessor.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLProgramCommon.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLProgramFactory.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLProgram.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLProgramManagerCommon.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLProgramPipeline.h \
	RenderSystems/GL3Plus/src/GLSL/include/OgreGLSLProgramPipelineManager.h \
	RenderSystems/GL3Plus/src/GLX/OgreGL3PlusUtil.h \
	RenderSystems/GL3Plus/src/gtk/OgreGL3PlusUtil.h \
	RenderSystems/GL/include/GL/glew.h \
	RenderSystems/GL/include/GL/glext.h \
	RenderSystems/GL/include/GL/gl.h \
	RenderSystems/GL/include/GL/glxew.h \
	RenderSystems/GL/include/GL/glxext.h \
	RenderSystems/GL/include/GL/glxtokens.h \
	RenderSystems/GL/include/GL/wglew.h \
	RenderSystems/GL/include/GL/wglext.h \
	RenderSystems/GL/include/GLX/OgreGLXContext.h \
	RenderSystems/GL/include/GLX/OgreGLXGLSupport.h \
	RenderSystems/GL/include/GLX/OgreGLXRenderTexture.h \
	RenderSystems/GL/include/GLX/OgreGLXUtils.h \
	RenderSystems/GL/include/GLX/OgreGLXWindow.h \
	RenderSystems/GL/include/OgreGLATIFSInit.h \
	RenderSystems/GL/include/OgreGLContext.h \
	RenderSystems/GL/include/OgreGLDefaultHardwareBufferManager.h \
	RenderSystems/GL/include/OgreGLDepthBuffer.h \
	RenderSystems/GL/include/OgreGLFBOMultiRenderTarget.h \
	RenderSystems/GL/include/OgreGLFBORenderTexture.h \
	RenderSystems/GL/include/OgreGLFrameBufferObject.h \
	RenderSystems/GL/include/OgreGLGpuNvparseProgram.h \
	RenderSystems/GL/include/OgreGLGpuProgram.h \
	RenderSystems/GL/include/OgreGLGpuProgramManager.h \
	RenderSystems/GL/include/OgreGLHardwareBufferManager.h \
	RenderSystems/GL/include/OgreGLHardwareIndexBuffer.h \
	RenderSystems/GL/include/OgreGLHardwareOcclusionQuery.h \
	RenderSystems/GL/include/OgreGLHardwarePixelBuffer.h \
	RenderSystems/GL/include/OgreGLHardwareVertexBuffer.h \
	RenderSystems/GL/include/OgreGLPBRenderTexture.h \
	RenderSystems/GL/include/OgreGLPBuffer.h \
	RenderSystems/GL/include/OgreGLPixelFormat.h \
	RenderSystems/GL/include/OgreGLPlugin.h \
	RenderSystems/GL/include/OgreGLPrerequisites.h \
	RenderSystems/GL/include/OgreGLRenderSystem.h \
	RenderSystems/GL/include/OgreGLRenderTexture.h \
	RenderSystems/GL/include/OgreGLRenderToVertexBuffer.h \
	RenderSystems/GL/include/OgreGLSupport.h \
	RenderSystems/GL/include/OgreGLTexture.h \
	RenderSystems/GL/include/OgreGLTextureManager.h \
	RenderSystems/GL/include/OgreSDLGLSupport.h \
	RenderSystems/GL/include/OgreSDLPrerequisites.h \
	RenderSystems/GL/src/atifs/include/ATI_FS_GLGpuProgram.h \
	RenderSystems/GL/src/atifs/include/Compiler2Pass.h \
	RenderSystems/GL/src/atifs/include/ps_1_4.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLExtSupport.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLGpuProgram.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLLinkProgram.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLLinkProgramManager.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLPreprocessor.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLProgramFactory.h \
	RenderSystems/GL/src/GLSL/include/OgreGLSLProgram.h \
	RenderSystems/GL/src/GLX/OgreGLUtil.h \
	RenderSystems/GL/src/gtk/OgreGLUtil.h \
	RenderSystems/GL/src/nvparse/macro.h \
	RenderSystems/GL/src/nvparse/nvparse_errors.h \
	RenderSystems/GL/src/nvparse/nvparse_externs.h \
	RenderSystems/GL/src/nvparse/nvparse.h \
	RenderSystems/GL/src/nvparse/_ps1.0_parser.h \
	RenderSystems/GL/src/nvparse/ps1.0_program.h \
	RenderSystems/GL/src/nvparse/rc1.0_combiners.h \
	RenderSystems/GL/src/nvparse/rc1.0_final.h \
	RenderSystems/GL/src/nvparse/rc1.0_general.h \
	RenderSystems/GL/src/nvparse/_rc1.0_parser.h \
	RenderSystems/GL/src/nvparse/rc1.0_register.h \
	RenderSystems/GL/src/nvparse/ts1.0_inst.h \
	RenderSystems/GL/src/nvparse/ts1.0_inst_list.h \
	RenderSystems/GL/src/nvparse/_ts1.0_parser.h \
	RenderSystems/GL/src/nvparse/vs1.0_inst.h \
	RenderSystems/GL/src/nvparse/vs1.0_inst_list.h \
	RenderSystems/GL/src/nvparse/_vs1.0_parser.h \
	RenderSystems/GL/src/SDL/OgreGLUtil.h \
	Tools/XMLConverter/include/OgreXMLMeshSerializer.h \
	Tools/XMLConverter/include/OgreXMLPrerequisites.h \
	Tools/XMLConverter/include/OgreXMLSkeletonSerializer.h \
	Tools/XMLConverter/include/tinystr.h \
	Tools/XMLConverter/include/tinyxml.h \

OGRE_INCLUDE_DIRS= \
	. \
	OgreMain/include \
	OgreMain/include/Threading \
	OgreMain/src/nedmalloc \
	RenderSystems/GL/src/GLX \
	RenderSystems/GL/src/StateCacheManager \
	RenderSystems/GL/src/nvparse \
	RenderSystems/GL/src/atifs/include \
	RenderSystems/GL/src/GLSL/include \
	RenderSystems/GL/include \
	RenderSystems/GL/include/GLX \
	RenderSystems/GL3Plus/include/GLSL \
	RenderSystems/GL3Plus/include \
	RenderSystems/GL3Plus/include/GLX \
	PlugIns/CgProgramManager/include \
	PlugIns/OctreeSceneManager/include \
	Tools/XMLConverter/include \
	Components/MeshLodGenerator/include \

OGRE_DEFS= \
	TIXML_USE_STL \

OGRE_LDLIBS= \
	-lm \
	-pthread \
	-ldl \
	-lCg \


XMLCONVERTER_WEAK_CPP_SRCS= \
	$(OGRESHARED_WEAK_CPP_SRCS) \
	Tools/XMLConverter/src/main.cpp \
	Tools/XMLConverter/src/OgreXMLSkeletonSerializer.cpp \
	Tools/XMLConverter/src/OgreXMLMeshSerializer.cpp \
	Tools/XMLConverter/src/tinyxml.cpp \
	Tools/XMLConverter/src/tinyxmlparser.cpp \
	Tools/XMLConverter/src/tinyxmlerror.cpp \
	Tools/XMLConverter/src/tinystr.cpp \

